services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    command: ['--replSet', 'rs0']
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}) }" | mongosh --port 27017 --quiet
